export const AUDIT_ACTIONS = {
  COMPANY_REGISTERED: "COMPANY_REGISTERED",
  COMPANY_REGISTER_FAILED: "COMPANY_REGISTER_FAILED",

  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",

  VERIFICATION_EMAIL_RESENT: "VERIFICATION_EMAIL_RESENT",
  VERIFICATION_EMAIL_RESEND_FAILED: "VERIFICATION_EMAIL_RESEND_FAILED",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  ADMIN_INVITED: "ADMIN_INVITED",
  ADMIN_INVITE_FAILED: "ADMIN_INVITE_FAILED",

  LOCAL_ADMIN_INVITED: "LOCAL_ADMIN_INVITED",
  LOCAL_ADMIN_INVITE_FAILED: "LOCAL_ADMIN_INVITE_FAILED",

  LOCAL_EVALUATOR_INVITED: "LOCAL_EVALUATOR_INVITED",
  LOCAL_EVALUATOR_INVITE_FAILED: "LOCAL_EVALUATOR_INVITE_FAILED",

  INVITATION_PASSWORD_CREATED: "INVITATION_PASSWORD_CREATED",
  INVITATION_PASSWORD_CREATION_FAILED: "INVITATION_PASSWORD_CREATION_FAILED",

  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_CHANGE_FAILED: "PASSWORD_CHANGE_FAILED",

  PASSWORD_RECOVERY_REQUESTED: "PASSWORD_RECOVERY_REQUESTED",
  PASSWORD_RECOVERY_FAILED: "PASSWORD_RECOVERY_FAILED",

  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",

  SESSION_CLOSED_BY_SECURITY_LINK: "SESSION_CLOSED_BY_SECURITY_LINK",
  SESSION_CLOSE_FAILED: "SESSION_CLOSE_FAILED",
} as const;

export const AUDIT_ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  RUC_ALREADY_EXISTS: "RUC_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_TOKEN: "INVALID_TOKEN",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  MUNICIPALITY_NOT_FOUND: "MUNICIPALITY_NOT_FOUND",
  ADMIN_NOT_FOUND: "ADMIN_NOT_FOUND",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_USED: "INVITATION_USED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_USED: "TOKEN_USED",
  SESSION_CLOSED: "SESSION_CLOSED",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;
